//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Loto.Models.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class lto_utilisateur
    {
        public lto_utilisateur()
        {
            this.lto_probabilite = new HashSet<lto_probabilite>();
        }
    
        public string uti_Pseudo { get; set; }
        public string uti_mdp { get; set; }
        public string uti_mail { get; set; }
    
        public virtual ICollection<lto_probabilite> lto_probabilite { get; set; }
    }
}
