//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Loto.Models.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class lto_tirage
    {
        public int tir_id { get; set; }
        public string tir_anneeTirage { get; set; }
        public int tir_idTirage { get; set; }
        public string tir_jourTirage { get; set; }
        public System.DateTime tir_dateTirage { get; set; }
        public Nullable<System.DateTime> tir_dateForclusion { get; set; }
        public Nullable<short> tir_boule1 { get; set; }
        public Nullable<short> tir_boule2 { get; set; }
        public Nullable<short> tir_boule3 { get; set; }
        public Nullable<short> tir_boule4 { get; set; }
        public Nullable<short> tir_boule5 { get; set; }
        public Nullable<short> tir_numeroChance { get; set; }
        public string tir_combinaisonGagnanteCroissant { get; set; }
        public Nullable<int> tir_nbrGagnantRang1 { get; set; }
        public Nullable<decimal> tir_rapportRang1 { get; set; }
        public Nullable<int> tir_nbrGagnantRang2 { get; set; }
        public Nullable<decimal> tir_rapportRang2 { get; set; }
        public Nullable<int> tir_nbrGagnantRang3 { get; set; }
        public Nullable<decimal> tir_rapportRang3 { get; set; }
        public Nullable<int> tir_nbrGagnantRang4 { get; set; }
        public Nullable<decimal> tir_rapportRang4 { get; set; }
        public Nullable<int> tir_nbrGagnantRang5 { get; set; }
        public Nullable<decimal> tir_rapportRang5 { get; set; }
        public Nullable<int> tir_nbrGagnantRang6 { get; set; }
        public Nullable<decimal> tir_rapportRang6 { get; set; }
        public string tir_numeroJokerplus { get; set; }
        public string tir_devise { get; set; }
        public Nullable<short> tir_premierOuSecondTirage { get; set; }
        public Nullable<short> tir_boule6 { get; set; }
        public Nullable<short> tir_bouleComplementaire { get; set; }
        public Nullable<int> tir_numeroJoker { get; set; }
        public Nullable<int> tir_nbrGagnantRang7 { get; set; }
        public Nullable<decimal> tir_rapportRang7 { get; set; }
    }
}
