//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Loto.Models.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class nouveau_loto
    {
        public int annee_numero_de_tirage { get; set; }
        public string jour_de_tirage { get; set; }
        public Nullable<System.DateTime> date_de_tirage { get; set; }
        public Nullable<System.DateTime> date_de_forclusion { get; set; }
        public Nullable<short> boule_1 { get; set; }
        public Nullable<short> boule_2 { get; set; }
        public Nullable<short> boule_3 { get; set; }
        public Nullable<short> boule_4 { get; set; }
        public Nullable<short> boule_5 { get; set; }
        public Nullable<short> numero_chance { get; set; }
        public string combinaison_gagnante_en_ordre_croissant { get; set; }
        public Nullable<int> nombre_de_gagnant_au_rang1 { get; set; }
        public Nullable<int> rapport_du_rang1 { get; set; }
        public Nullable<int> nombre_de_gagnant_au_rang2 { get; set; }
        public Nullable<int> rapport_du_rang2 { get; set; }
        public Nullable<int> nombre_de_gagnant_au_rang3 { get; set; }
        public Nullable<int> rapport_du_rang3 { get; set; }
        public Nullable<int> nombre_de_gagnant_au_rang4 { get; set; }
        public Nullable<int> rapport_du_rang4 { get; set; }
        public Nullable<int> nombre_de_gagnant_au_rang5 { get; set; }
        public Nullable<int> rapport_du_rang5 { get; set; }
        public Nullable<int> nombre_de_gagnant_au_rang6 { get; set; }
        public Nullable<int> rapport_du_rang6 { get; set; }
        public string numero_jokerplus { get; set; }
        public string devise { get; set; }
        public string Column_25 { get; set; }
    }
}
