// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments and CLS compliance
// 0108: suppress "Foo hides inherited member Foo. Use the new keyword if hiding was intended." when a controller and its abstract parent are both processed
#pragma warning disable 1591, 3008, 3009, 0108
#region T4MVC

using System;
using System.Diagnostics;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Threading.Tasks;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;
using System.Web.Mvc.Html;
using System.Web.Routing;
using T4MVC;
namespace BootstrapMvcSample.Controllers
{
    public partial class ExampleLayoutsController
    {
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ExampleLayoutsController() { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected ExampleLayoutsController(Dummy d) { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoute(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(Task<ActionResult> taskResult)
        {
            return RedirectToAction(taskResult.Result);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoutePermanent(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(Task<ActionResult> taskResult)
        {
            return RedirectToActionPermanent(taskResult.Result);
        }


        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ExampleLayoutsController Actions { get { return MVC.ExampleLayouts; } }
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Area = "";
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Name = "ExampleLayouts";
        [GeneratedCode("T4MVC", "2.0")]
        public const string NameConst = "ExampleLayouts";

        static readonly ActionNamesClass s_actions = new ActionNamesClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionNamesClass ActionNames { get { return s_actions; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNamesClass
        {
            public readonly string Starter = "Starter";
            public readonly string Marketing = "Marketing";
            public readonly string Fluid = "Fluid";
            public readonly string Narrow = "Narrow";
            public readonly string SignIn = "SignIn";
            public readonly string StickyFooter = "StickyFooter";
            public readonly string Carousel = "Carousel";
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNameConstants
        {
            public const string Starter = "Starter";
            public const string Marketing = "Marketing";
            public const string Fluid = "Fluid";
            public const string Narrow = "Narrow";
            public const string SignIn = "SignIn";
            public const string StickyFooter = "StickyFooter";
            public const string Carousel = "Carousel";
        }


        static readonly ViewsClass s_views = new ViewsClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ViewsClass Views { get { return s_views; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ViewsClass
        {
            static readonly _ViewNamesClass s_ViewNames = new _ViewNamesClass();
            public _ViewNamesClass ViewNames { get { return s_ViewNames; } }
            public class _ViewNamesClass
            {
                public readonly string Fluid = "Fluid";
                public readonly string Marketing = "Marketing";
                public readonly string Narrow = "Narrow";
                public readonly string SignIn = "SignIn";
                public readonly string Starter = "Starter";
                public readonly string TBD = "TBD";
            }
            public readonly string Fluid = "~/Views/ExampleLayouts/Fluid.cshtml";
            public readonly string Marketing = "~/Views/ExampleLayouts/Marketing.cshtml";
            public readonly string Narrow = "~/Views/ExampleLayouts/Narrow.cshtml";
            public readonly string SignIn = "~/Views/ExampleLayouts/SignIn.cshtml";
            public readonly string Starter = "~/Views/ExampleLayouts/Starter.cshtml";
            public readonly string TBD = "~/Views/ExampleLayouts/TBD.cshtml";
        }
    }

    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public partial class T4MVC_ExampleLayoutsController : BootstrapMvcSample.Controllers.ExampleLayoutsController
    {
        public T4MVC_ExampleLayoutsController() : base(Dummy.Instance) { }

        [NonAction]
        partial void StarterOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult Starter()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Starter);
            StarterOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void MarketingOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult Marketing()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Marketing);
            MarketingOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void FluidOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult Fluid()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Fluid);
            FluidOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void NarrowOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult Narrow()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Narrow);
            NarrowOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void SignInOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult SignIn()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.SignIn);
            SignInOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void StickyFooterOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult StickyFooter()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.StickyFooter);
            StickyFooterOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void CarouselOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult Carousel()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Carousel);
            CarouselOverride(callInfo);
            return callInfo;
        }

    }
}

#endregion T4MVC
#pragma warning restore 1591, 3008, 3009, 0108
