// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments and CLS compliance
// 0108: suppress "Foo hides inherited member Foo. Use the new keyword if hiding was intended." when a controller and its abstract parent are both processed
#pragma warning disable 1591, 3008, 3009, 0108
#region T4MVC

using System;
using System.Diagnostics;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Threading.Tasks;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;
using System.Web.Mvc.Html;
using System.Web.Routing;
using T4MVC;
namespace T4MVC
{
    public class sharedController
    {

        static readonly ViewsClass s_views = new ViewsClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ViewsClass Views { get { return s_views; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ViewsClass
        {
            static readonly _ViewNamesClass s_ViewNames = new _ViewNamesClass();
            public _ViewNamesClass ViewNames { get { return s_ViewNames; } }
            public class _ViewNamesClass
            {
                public readonly string _alerts = "_alerts";
                public readonly string _BootstrapLayout_basic = "_BootstrapLayout.basic";
                public readonly string _BootstrapLayout_empty = "_BootstrapLayout.empty";
                public readonly string _BootstrapLayout_narrow = "_BootstrapLayout.narrow";
                public readonly string _html5shiv = "_html5shiv";
                public readonly string _validationSummary = "_validationSummary";
                public readonly string Create = "Create";
                public readonly string Details = "Details";
                public readonly string Index = "Index";
            }
            public readonly string _alerts = "~/Views/shared/_alerts.cshtml";
            public readonly string _BootstrapLayout_basic = "~/Views/shared/_BootstrapLayout.basic.cshtml";
            public readonly string _BootstrapLayout_empty = "~/Views/shared/_BootstrapLayout.empty.cshtml";
            public readonly string _BootstrapLayout_narrow = "~/Views/shared/_BootstrapLayout.narrow.cshtml";
            public readonly string _html5shiv = "~/Views/shared/_html5shiv.cshtml";
            public readonly string _validationSummary = "~/Views/shared/_validationSummary.cshtml";
            public readonly string Create = "~/Views/shared/Create.cshtml";
            public readonly string Details = "~/Views/shared/Details.cshtml";
            public readonly string Index = "~/Views/shared/Index.cshtml";
        }
    }

}

#endregion T4MVC
#pragma warning restore 1591, 3008, 3009, 0108
