// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments and CLS compliance
// 0108: suppress "Foo hides inherited member Foo. Use the new keyword if hiding was intended." when a controller and its abstract parent are both processed
#pragma warning disable 1591, 3008, 3009, 0108
#region T4MVC

using System;
using System.Diagnostics;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Threading.Tasks;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;
using System.Web.Mvc.Html;
using System.Web.Routing;
using T4MVC;

[GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
public static partial class MVC
{
    public static Loto.Controllers.HomeController Home = new Loto.Controllers.T4MVC_HomeController();
    public static Loto.Controllers.ResultatController Resultat = new Loto.Controllers.T4MVC_ResultatController();
    public static T4MVC.SharedController Shared = new T4MVC.SharedController();
}

namespace T4MVC
{
}

namespace T4MVC
{
    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public class Dummy
    {
        private Dummy() { }
        public static Dummy Instance = new Dummy();
    }
}

[GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
internal partial class T4MVC_System_Web_Mvc_ActionResult : System.Web.Mvc.ActionResult, IT4MVCActionResult
{
    public T4MVC_System_Web_Mvc_ActionResult(string area, string controller, string action, string protocol = null): base()
    {
        this.InitMVCT4Result(area, controller, action, protocol);
    }
     
    public override void ExecuteResult(System.Web.Mvc.ControllerContext context) { }
    
    public string Controller { get; set; }
    public string Action { get; set; }
    public string Protocol { get; set; }
    public RouteValueDictionary RouteValueDictionary { get; set; }
}



namespace Links
{
    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public static class Scripts {
        private const string URLPATH = "~/Scripts";
        public static string Url() { return T4MVCHelpers.ProcessVirtualPath(URLPATH); }
        public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(URLPATH + "/" + fileName); }
        public static readonly string bootstrap_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/bootstrap.min.js") ? Url("bootstrap.min.js") : Url("bootstrap.js");
        public static readonly string bootstrap_min_js = Url("bootstrap.min.js");
        public static readonly string html5shiv_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/html5shiv.min.js") ? Url("html5shiv.min.js") : Url("html5shiv.js");
        public static readonly string jquery_1_9_1_intellisense_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/jquery-1.9.1.intellisense.min.js") ? Url("jquery-1.9.1.intellisense.min.js") : Url("jquery-1.9.1.intellisense.js");
        public static readonly string jquery_1_9_1_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/jquery-1.9.1.min.js") ? Url("jquery-1.9.1.min.js") : Url("jquery-1.9.1.js");
        public static readonly string jquery_1_9_1_min_js = Url("jquery-1.9.1.min.js");
        public static readonly string jquery_1_9_1_min_map = Url("jquery-1.9.1.min.map");
        public static readonly string jquery_migrate_1_2_1_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/jquery-migrate-1.2.1.min.js") ? Url("jquery-migrate-1.2.1.min.js") : Url("jquery-migrate-1.2.1.js");
        public static readonly string jquery_migrate_1_2_1_min_js = Url("jquery-migrate-1.2.1.min.js");
        public static readonly string jquery_unobtrusive_ajax_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/jquery.unobtrusive-ajax.min.js") ? Url("jquery.unobtrusive-ajax.min.js") : Url("jquery.unobtrusive-ajax.js");
        public static readonly string jquery_unobtrusive_ajax_min_js = Url("jquery.unobtrusive-ajax.min.js");
        public static readonly string jquery_validate_vsdoc_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/jquery.validate-vsdoc.min.js") ? Url("jquery.validate-vsdoc.min.js") : Url("jquery.validate-vsdoc.js");
        public static readonly string jquery_validate_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/jquery.validate.min.js") ? Url("jquery.validate.min.js") : Url("jquery.validate.js");
        public static readonly string jquery_validate_min_js = Url("jquery.validate.min.js");
        public static readonly string jquery_validate_unobtrusive_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/jquery.validate.unobtrusive.min.js") ? Url("jquery.validate.unobtrusive.min.js") : Url("jquery.validate.unobtrusive.js");
        public static readonly string jquery_validate_unobtrusive_min_js = Url("jquery.validate.unobtrusive.min.js");
        public static readonly string npm_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/npm.min.js") ? Url("npm.min.js") : Url("npm.js");
    }

    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public static class Content {
        private const string URLPATH = "~/Content";
        public static string Url() { return T4MVCHelpers.ProcessVirtualPath(URLPATH); }
        public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(URLPATH + "/" + fileName); }
        public static readonly string animate_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/animate.min.css") ? Url("animate.min.css") : Url("animate.css");
             
        public static readonly string animate_min_css = Url("animate.min.css");
        public static readonly string awesome_bootstrap_checkbox_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/awesome-bootstrap-checkbox.min.css") ? Url("awesome-bootstrap-checkbox.min.css") : Url("awesome-bootstrap-checkbox.css");
             
        public static readonly string bootstrap_theme_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/bootstrap-theme.min.css") ? Url("bootstrap-theme.min.css") : Url("bootstrap-theme.css");
             
        public static readonly string bootstrap_theme_css_map = Url("bootstrap-theme.css.map");
        public static readonly string bootstrap_theme_min_css = Url("bootstrap-theme.min.css");
        public static readonly string bootstrap_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/bootstrap.min.css") ? Url("bootstrap.min.css") : Url("bootstrap.css");
             
        public static readonly string bootstrap_css_map = Url("bootstrap.css.map");
        public static readonly string bootstrap_min_css = Url("bootstrap.min.css");
        public static readonly string font_awesome_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/font-awesome.min.css") ? Url("font-awesome.min.css") : Url("font-awesome.css");
             
        public static readonly string font_awesome_min_css = Url("font-awesome.min.css");
        public static readonly string hover_min_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/hover-min.min.css") ? Url("hover-min.min.css") : Url("hover-min.css");
             
        public static readonly string hover_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/hover.min.css") ? Url("hover.min.css") : Url("hover.css");
             
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public static class images {
            private const string URLPATH = "~/Content/images";
            public static string Url() { return T4MVCHelpers.ProcessVirtualPath(URLPATH); }
            public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(URLPATH + "/" + fileName); }
            public static readonly string glyphicons_halflings_white_png = Url("glyphicons-halflings-white.png");
            public static readonly string glyphicons_halflings_png = Url("glyphicons-halflings.png");
        }
    
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public static class less {
            private const string URLPATH = "~/Content/less";
            public static string Url() { return T4MVCHelpers.ProcessVirtualPath(URLPATH); }
            public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(URLPATH + "/" + fileName); }
            public static readonly string _hacks_less = Url("_hacks.less");
            public static readonly string _mixins_less = Url("_mixins.less");
            public static readonly string _options_less = Url("_options.less");
            [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
            public static class effects {
                private const string URLPATH = "~/Content/less/effects";
                public static string Url() { return T4MVCHelpers.ProcessVirtualPath(URLPATH); }
                public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(URLPATH + "/" + fileName); }
                [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
                public static class _2d_transitions {
                    private const string URLPATH = "~/Content/less/effects/2d-transitions";
                    public static string Url() { return T4MVCHelpers.ProcessVirtualPath(URLPATH); }
                    public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(URLPATH + "/" + fileName); }
                    public static readonly string _bob_less = Url("_bob.less");
                    public static readonly string _bounce_in_less = Url("_bounce-in.less");
                    public static readonly string _bounce_out_less = Url("_bounce-out.less");
                    public static readonly string _buzz_out_less = Url("_buzz-out.less");
                    public static readonly string _buzz_less = Url("_buzz.less");
                    public static readonly string _float_less = Url("_float.less");
                    public static readonly string _grow_rotate_less = Url("_grow-rotate.less");
                    public static readonly string _grow_less = Url("_grow.less");
                    public static readonly string _hang_less = Url("_hang.less");
                    public static readonly string _pop_less = Url("_pop.less");
                    public static readonly string _pulse_grow_less = Url("_pulse-grow.less");
                    public static readonly string _pulse_shrink_less = Url("_pulse-shrink.less");
                    public static readonly string _pulse_less = Url("_pulse.less");
                    public static readonly string _push_less = Url("_push.less");
                    public static readonly string _rotate_less = Url("_rotate.less");
                    public static readonly string _shrink_less = Url("_shrink.less");
                    public static readonly string _sink_less = Url("_sink.less");
                    public static readonly string _skew_backward_less = Url("_skew-backward.less");
                    public static readonly string _skew_forward_less = Url("_skew-forward.less");
                    public static readonly string _skew_less = Url("_skew.less");
                    public static readonly string _wobble_bottom_less = Url("_wobble-bottom.less");
                    public static readonly string _wobble_horizontal_less = Url("_wobble-horizontal.less");
                    public static readonly string _wobble_skew_less = Url("_wobble-skew.less");
                    public static readonly string _wobble_to_bottom_right_less = Url("_wobble-to-bottom-right.less");
                    public static readonly string _wobble_to_top_right_less = Url("_wobble-to-top-right.less");
                    public static readonly string _wobble_top_less = Url("_wobble-top.less");
                    public static readonly string _wobble_vertical_less = Url("_wobble-vertical.less");
                }
            
                [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
                public static class background_transitions {
                    private const string URLPATH = "~/Content/less/effects/background-transitions";
                    public static string Url() { return T4MVCHelpers.ProcessVirtualPath(URLPATH); }
                    public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(URLPATH + "/" + fileName); }
                    public static readonly string _back_pulse_less = Url("_back-pulse.less");
                    public static readonly string _bounce_to_bottom_less = Url("_bounce-to-bottom.less");
                    public static readonly string _bounce_to_left_less = Url("_bounce-to-left.less");
                    public static readonly string _bounce_to_right_less = Url("_bounce-to-right.less");
                    public static readonly string _bounce_to_top_less = Url("_bounce-to-top.less");
                    public static readonly string _fade_less = Url("_fade.less");
                    public static readonly string _radial_in_less = Url("_radial-in.less");
                    public static readonly string _radial_out_less = Url("_radial-out.less");
                    public static readonly string _rectangle_in_less = Url("_rectangle-in.less");
                    public static readonly string _rectangle_out_less = Url("_rectangle-out.less");
                    public static readonly string _shutter_in_horizontal_less = Url("_shutter-in-horizontal.less");
                    public static readonly string _shutter_in_vertical_less = Url("_shutter-in-vertical.less");
                    public static readonly string _shutter_out_horizontal_less = Url("_shutter-out-horizontal.less");
                    public static readonly string _shutter_out_vertical_less = Url("_shutter-out-vertical.less");
                    public static readonly string _sweep_to_bottom_less = Url("_sweep-to-bottom.less");
                    public static readonly string _sweep_to_left_less = Url("_sweep-to-left.less");
                    public static readonly string _sweep_to_right_less = Url("_sweep-to-right.less");
                    public static readonly string _sweep_to_top_less = Url("_sweep-to-top.less");
                }
            
                [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
                public static class border_transitions {
                    private const string URLPATH = "~/Content/less/effects/border-transitions";
                    public static string Url() { return T4MVCHelpers.ProcessVirtualPath(URLPATH); }
                    public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(URLPATH + "/" + fileName); }
                    public static readonly string _border_fade_less = Url("_border-fade.less");
                    public static readonly string _hollow_less = Url("_hollow.less");
                    public static readonly string _outline_in_less = Url("_outline-in.less");
                    public static readonly string _outline_out_less = Url("_outline-out.less");
                    public static readonly string _overline_from_center_less = Url("_overline-from-center.less");
                    public static readonly string _overline_from_left_less = Url("_overline-from-left.less");
                    public static readonly string _overline_from_right_less = Url("_overline-from-right.less");
                    public static readonly string _overline_reveal_less = Url("_overline-reveal.less");
                    public static readonly string _reveal_less = Url("_reveal.less");
                    public static readonly string _ripple_in_less = Url("_ripple-in.less");
                    public static readonly string _ripple_out_less = Url("_ripple-out.less");
                    public static readonly string _round_corners_less = Url("_round-corners.less");
                    public static readonly string _trim_less = Url("_trim.less");
                    public static readonly string _underline_from_center_less = Url("_underline-from-center.less");
                    public static readonly string _underline_from_left_less = Url("_underline-from-left.less");
                    public static readonly string _underline_from_right_less = Url("_underline-from-right.less");
                    public static readonly string _underline_reveal_less = Url("_underline-reveal.less");
                }
            
                [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
                public static class curls {
                    private const string URLPATH = "~/Content/less/effects/curls";
                    public static string Url() { return T4MVCHelpers.ProcessVirtualPath(URLPATH); }
                    public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(URLPATH + "/" + fileName); }
                    public static readonly string _curl_bottom_left_less = Url("_curl-bottom-left.less");
                    public static readonly string _curl_bottom_right_less = Url("_curl-bottom-right.less");
                    public static readonly string _curl_top_left_less = Url("_curl-top-left.less");
                    public static readonly string _curl_top_right_less = Url("_curl-top-right.less");
                }
            
                [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
                public static class icons {
                    private const string URLPATH = "~/Content/less/effects/icons";
                    public static string Url() { return T4MVCHelpers.ProcessVirtualPath(URLPATH); }
                    public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(URLPATH + "/" + fileName); }
                    public static readonly string _icon_back_less = Url("_icon-back.less");
                    public static readonly string _icon_bob_less = Url("_icon-bob.less");
                    public static readonly string _icon_bounce_out_less = Url("_icon-bounce-out.less");
                    public static readonly string _icon_bounce_less = Url("_icon-bounce.less");
                    public static readonly string _icon_buzz_out_less = Url("_icon-buzz-out.less");
                    public static readonly string _icon_buzz_less = Url("_icon-buzz.less");
                    public static readonly string _icon_down_less = Url("_icon-down.less");
                    public static readonly string _icon_drop_less = Url("_icon-drop.less");
                    public static readonly string _icon_fade_less = Url("_icon-fade.less");
                    public static readonly string _icon_float_away_less = Url("_icon-float-away.less");
                    public static readonly string _icon_float_less = Url("_icon-float.less");
                    public static readonly string _icon_forward_less = Url("_icon-forward.less");
                    public static readonly string _icon_grow_rotate_less = Url("_icon-grow-rotate.less");
                    public static readonly string _icon_grow_less = Url("_icon-grow.less");
                    public static readonly string _icon_hang_less = Url("_icon-hang.less");
                    public static readonly string _icon_pop_less = Url("_icon-pop.less");
                    public static readonly string _icon_pulse_grow_less = Url("_icon-pulse-grow.less");
                    public static readonly string _icon_pulse_shrink_less = Url("_icon-pulse-shrink.less");
                    public static readonly string _icon_pulse_less = Url("_icon-pulse.less");
                    public static readonly string _icon_push_less = Url("_icon-push.less");
                    public static readonly string _icon_rotate_less = Url("_icon-rotate.less");
                    public static readonly string _icon_shrink_less = Url("_icon-shrink.less");
                    public static readonly string _icon_sink_away_less = Url("_icon-sink-away.less");
                    public static readonly string _icon_sink_less = Url("_icon-sink.less");
                    public static readonly string _icon_spin_less = Url("_icon-spin.less");
                    public static readonly string _icon_up_less = Url("_icon-up.less");
                    public static readonly string _icon_wobble_horizontal_less = Url("_icon-wobble-horizontal.less");
                    public static readonly string _icon_wobble_vertical_less = Url("_icon-wobble-vertical.less");
                }
            
                [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
                public static class shadow_and_glow_transitions {
                    private const string URLPATH = "~/Content/less/effects/shadow-and-glow-transitions";
                    public static string Url() { return T4MVCHelpers.ProcessVirtualPath(URLPATH); }
                    public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(URLPATH + "/" + fileName); }
                    public static readonly string _box_shadow_inset_less = Url("_box-shadow-inset.less");
                    public static readonly string _box_shadow_outset_less = Url("_box-shadow-outset.less");
                    public static readonly string _float_shadow_less = Url("_float-shadow.less");
                    public static readonly string _glow_less = Url("_glow.less");
                    public static readonly string _grow_shadow_less = Url("_grow-shadow.less");
                    public static readonly string _shadow_radial_less = Url("_shadow-radial.less");
                    public static readonly string _shadow_less = Url("_shadow.less");
                }
            
                [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
                public static class speech_bubbles {
                    private const string URLPATH = "~/Content/less/effects/speech-bubbles";
                    public static string Url() { return T4MVCHelpers.ProcessVirtualPath(URLPATH); }
                    public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(URLPATH + "/" + fileName); }
                    public static readonly string _bubble_bottom_less = Url("_bubble-bottom.less");
                    public static readonly string _bubble_float_bottom_less = Url("_bubble-float-bottom.less");
                    public static readonly string _bubble_float_left_less = Url("_bubble-float-left.less");
                    public static readonly string _bubble_float_right_less = Url("_bubble-float-right.less");
                    public static readonly string _bubble_float_top_less = Url("_bubble-float-top.less");
                    public static readonly string _bubble_left_less = Url("_bubble-left.less");
                    public static readonly string _bubble_right_less = Url("_bubble-right.less");
                    public static readonly string _bubble_top_less = Url("_bubble-top.less");
                }
            
            }
        
            public static readonly string hover_less = Url("hover.less");
        }
    
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public static class scss {
            private const string URLPATH = "~/Content/scss";
            public static string Url() { return T4MVCHelpers.ProcessVirtualPath(URLPATH); }
            public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(URLPATH + "/" + fileName); }
            public static readonly string _hacks_scss = Url("_hacks.scss");
            public static readonly string _mixins_scss = Url("_mixins.scss");
            public static readonly string _options_scss = Url("_options.scss");
            [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
            public static class effects {
                private const string URLPATH = "~/Content/scss/effects";
                public static string Url() { return T4MVCHelpers.ProcessVirtualPath(URLPATH); }
                public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(URLPATH + "/" + fileName); }
                [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
                public static class _2d_transitions {
                    private const string URLPATH = "~/Content/scss/effects/2d-transitions";
                    public static string Url() { return T4MVCHelpers.ProcessVirtualPath(URLPATH); }
                    public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(URLPATH + "/" + fileName); }
                    public static readonly string _bob_scss = Url("_bob.scss");
                    public static readonly string _bounce_in_scss = Url("_bounce-in.scss");
                    public static readonly string _bounce_out_scss = Url("_bounce-out.scss");
                    public static readonly string _buzz_out_scss = Url("_buzz-out.scss");
                    public static readonly string _buzz_scss = Url("_buzz.scss");
                    public static readonly string _float_scss = Url("_float.scss");
                    public static readonly string _grow_rotate_scss = Url("_grow-rotate.scss");
                    public static readonly string _grow_scss = Url("_grow.scss");
                    public static readonly string _hang_scss = Url("_hang.scss");
                    public static readonly string _pop_scss = Url("_pop.scss");
                    public static readonly string _pulse_grow_scss = Url("_pulse-grow.scss");
                    public static readonly string _pulse_shrink_scss = Url("_pulse-shrink.scss");
                    public static readonly string _pulse_scss = Url("_pulse.scss");
                    public static readonly string _push_scss = Url("_push.scss");
                    public static readonly string _rotate_scss = Url("_rotate.scss");
                    public static readonly string _shrink_scss = Url("_shrink.scss");
                    public static readonly string _sink_scss = Url("_sink.scss");
                    public static readonly string _skew_backward_scss = Url("_skew-backward.scss");
                    public static readonly string _skew_forward_scss = Url("_skew-forward.scss");
                    public static readonly string _skew_scss = Url("_skew.scss");
                    public static readonly string _wobble_bottom_scss = Url("_wobble-bottom.scss");
                    public static readonly string _wobble_horizontal_scss = Url("_wobble-horizontal.scss");
                    public static readonly string _wobble_skew_scss = Url("_wobble-skew.scss");
                    public static readonly string _wobble_to_bottom_right_scss = Url("_wobble-to-bottom-right.scss");
                    public static readonly string _wobble_to_top_right_scss = Url("_wobble-to-top-right.scss");
                    public static readonly string _wobble_top_scss = Url("_wobble-top.scss");
                    public static readonly string _wobble_vertical_scss = Url("_wobble-vertical.scss");
                }
            
                [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
                public static class background_transitions {
                    private const string URLPATH = "~/Content/scss/effects/background-transitions";
                    public static string Url() { return T4MVCHelpers.ProcessVirtualPath(URLPATH); }
                    public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(URLPATH + "/" + fileName); }
                    public static readonly string _back_pulse_scss = Url("_back-pulse.scss");
                    public static readonly string _bounce_to_bottom_scss = Url("_bounce-to-bottom.scss");
                    public static readonly string _bounce_to_left_scss = Url("_bounce-to-left.scss");
                    public static readonly string _bounce_to_right_scss = Url("_bounce-to-right.scss");
                    public static readonly string _bounce_to_top_scss = Url("_bounce-to-top.scss");
                    public static readonly string _fade_scss = Url("_fade.scss");
                    public static readonly string _radial_in_scss = Url("_radial-in.scss");
                    public static readonly string _radial_out_scss = Url("_radial-out.scss");
                    public static readonly string _rectangle_in_scss = Url("_rectangle-in.scss");
                    public static readonly string _rectangle_out_scss = Url("_rectangle-out.scss");
                    public static readonly string _shutter_in_horizontal_scss = Url("_shutter-in-horizontal.scss");
                    public static readonly string _shutter_in_vertical_scss = Url("_shutter-in-vertical.scss");
                    public static readonly string _shutter_out_horizontal_scss = Url("_shutter-out-horizontal.scss");
                    public static readonly string _shutter_out_vertical_scss = Url("_shutter-out-vertical.scss");
                    public static readonly string _sweep_to_bottom_scss = Url("_sweep-to-bottom.scss");
                    public static readonly string _sweep_to_left_scss = Url("_sweep-to-left.scss");
                    public static readonly string _sweep_to_right_scss = Url("_sweep-to-right.scss");
                    public static readonly string _sweep_to_top_scss = Url("_sweep-to-top.scss");
                }
            
                [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
                public static class border_transitions {
                    private const string URLPATH = "~/Content/scss/effects/border-transitions";
                    public static string Url() { return T4MVCHelpers.ProcessVirtualPath(URLPATH); }
                    public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(URLPATH + "/" + fileName); }
                    public static readonly string _border_fade_scss = Url("_border-fade.scss");
                    public static readonly string _hollow_scss = Url("_hollow.scss");
                    public static readonly string _outline_in_scss = Url("_outline-in.scss");
                    public static readonly string _outline_out_scss = Url("_outline-out.scss");
                    public static readonly string _overline_from_center_scss = Url("_overline-from-center.scss");
                    public static readonly string _overline_from_left_scss = Url("_overline-from-left.scss");
                    public static readonly string _overline_from_right_scss = Url("_overline-from-right.scss");
                    public static readonly string _overline_reveal_scss = Url("_overline-reveal.scss");
                    public static readonly string _reveal_scss = Url("_reveal.scss");
                    public static readonly string _ripple_in_scss = Url("_ripple-in.scss");
                    public static readonly string _ripple_out_scss = Url("_ripple-out.scss");
                    public static readonly string _round_corners_scss = Url("_round-corners.scss");
                    public static readonly string _trim_scss = Url("_trim.scss");
                    public static readonly string _underline_from_center_scss = Url("_underline-from-center.scss");
                    public static readonly string _underline_from_left_scss = Url("_underline-from-left.scss");
                    public static readonly string _underline_from_right_scss = Url("_underline-from-right.scss");
                    public static readonly string _underline_reveal_scss = Url("_underline-reveal.scss");
                }
            
                [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
                public static class curls {
                    private const string URLPATH = "~/Content/scss/effects/curls";
                    public static string Url() { return T4MVCHelpers.ProcessVirtualPath(URLPATH); }
                    public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(URLPATH + "/" + fileName); }
                    public static readonly string _curl_bottom_left_scss = Url("_curl-bottom-left.scss");
                    public static readonly string _curl_bottom_right_scss = Url("_curl-bottom-right.scss");
                    public static readonly string _curl_top_left_scss = Url("_curl-top-left.scss");
                    public static readonly string _curl_top_right_scss = Url("_curl-top-right.scss");
                }
            
                [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
                public static class icons {
                    private const string URLPATH = "~/Content/scss/effects/icons";
                    public static string Url() { return T4MVCHelpers.ProcessVirtualPath(URLPATH); }
                    public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(URLPATH + "/" + fileName); }
                    public static readonly string _icon_back_scss = Url("_icon-back.scss");
                    public static readonly string _icon_bob_scss = Url("_icon-bob.scss");
                    public static readonly string _icon_bounce_out_scss = Url("_icon-bounce-out.scss");
                    public static readonly string _icon_bounce_scss = Url("_icon-bounce.scss");
                    public static readonly string _icon_buzz_out_scss = Url("_icon-buzz-out.scss");
                    public static readonly string _icon_buzz_scss = Url("_icon-buzz.scss");
                    public static readonly string _icon_down_scss = Url("_icon-down.scss");
                    public static readonly string _icon_drop_scss = Url("_icon-drop.scss");
                    public static readonly string _icon_fade_scss = Url("_icon-fade.scss");
                    public static readonly string _icon_float_away_scss = Url("_icon-float-away.scss");
                    public static readonly string _icon_float_scss = Url("_icon-float.scss");
                    public static readonly string _icon_forward_scss = Url("_icon-forward.scss");
                    public static readonly string _icon_grow_rotate_scss = Url("_icon-grow-rotate.scss");
                    public static readonly string _icon_grow_scss = Url("_icon-grow.scss");
                    public static readonly string _icon_hang_scss = Url("_icon-hang.scss");
                    public static readonly string _icon_pop_scss = Url("_icon-pop.scss");
                    public static readonly string _icon_pulse_grow_scss = Url("_icon-pulse-grow.scss");
                    public static readonly string _icon_pulse_shrink_scss = Url("_icon-pulse-shrink.scss");
                    public static readonly string _icon_pulse_scss = Url("_icon-pulse.scss");
                    public static readonly string _icon_push_scss = Url("_icon-push.scss");
                    public static readonly string _icon_rotate_scss = Url("_icon-rotate.scss");
                    public static readonly string _icon_shrink_scss = Url("_icon-shrink.scss");
                    public static readonly string _icon_sink_away_scss = Url("_icon-sink-away.scss");
                    public static readonly string _icon_sink_scss = Url("_icon-sink.scss");
                    public static readonly string _icon_spin_scss = Url("_icon-spin.scss");
                    public static readonly string _icon_up_scss = Url("_icon-up.scss");
                    public static readonly string _icon_wobble_horizontal_scss = Url("_icon-wobble-horizontal.scss");
                    public static readonly string _icon_wobble_vertical_scss = Url("_icon-wobble-vertical.scss");
                }
            
                [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
                public static class shadow_and_glow_transitions {
                    private const string URLPATH = "~/Content/scss/effects/shadow-and-glow-transitions";
                    public static string Url() { return T4MVCHelpers.ProcessVirtualPath(URLPATH); }
                    public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(URLPATH + "/" + fileName); }
                    public static readonly string _box_shadow_inset_scss = Url("_box-shadow-inset.scss");
                    public static readonly string _box_shadow_outset_scss = Url("_box-shadow-outset.scss");
                    public static readonly string _float_shadow_scss = Url("_float-shadow.scss");
                    public static readonly string _glow_scss = Url("_glow.scss");
                    public static readonly string _grow_shadow_scss = Url("_grow-shadow.scss");
                    public static readonly string _shadow_radial_scss = Url("_shadow-radial.scss");
                    public static readonly string _shadow_scss = Url("_shadow.scss");
                }
            
                [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
                public static class speech_bubbles {
                    private const string URLPATH = "~/Content/scss/effects/speech-bubbles";
                    public static string Url() { return T4MVCHelpers.ProcessVirtualPath(URLPATH); }
                    public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(URLPATH + "/" + fileName); }
                    public static readonly string _bubble_bottom_scss = Url("_bubble-bottom.scss");
                    public static readonly string _bubble_float_bottom_scss = Url("_bubble-float-bottom.scss");
                    public static readonly string _bubble_float_left_scss = Url("_bubble-float-left.scss");
                    public static readonly string _bubble_float_right_scss = Url("_bubble-float-right.scss");
                    public static readonly string _bubble_float_top_scss = Url("_bubble-float-top.scss");
                    public static readonly string _bubble_left_scss = Url("_bubble-left.scss");
                    public static readonly string _bubble_right_scss = Url("_bubble-right.scss");
                    public static readonly string _bubble_top_scss = Url("_bubble-top.scss");
                }
            
            }
        
            public static readonly string hover_scss = Url("hover.scss");
        }
    
    }

    
    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public static partial class Bundles
    {
        public static partial class Scripts 
        {
            public static class Assets
            {
                public const string bootstrap_js = "~/Scripts/bootstrap.js"; 
                public const string bootstrap_min_js = "~/Scripts/bootstrap.min.js"; 
                public const string html5shiv_js = "~/Scripts/html5shiv.js"; 
                public const string jquery_1_9_1_intellisense_js = "~/Scripts/jquery-1.9.1.intellisense.js"; 
                public const string jquery_1_9_1_js = "~/Scripts/jquery-1.9.1.js"; 
                public const string jquery_1_9_1_min_js = "~/Scripts/jquery-1.9.1.min.js"; 
                public const string jquery_migrate_1_2_1_js = "~/Scripts/jquery-migrate-1.2.1.js"; 
                public const string jquery_migrate_1_2_1_min_js = "~/Scripts/jquery-migrate-1.2.1.min.js"; 
                public const string jquery_unobtrusive_ajax_js = "~/Scripts/jquery.unobtrusive-ajax.js"; 
                public const string jquery_unobtrusive_ajax_min_js = "~/Scripts/jquery.unobtrusive-ajax.min.js"; 
                public const string jquery_validate_js = "~/Scripts/jquery.validate.js"; 
                public const string jquery_validate_min_js = "~/Scripts/jquery.validate.min.js"; 
                public const string jquery_validate_unobtrusive_js = "~/Scripts/jquery.validate.unobtrusive.js"; 
                public const string jquery_validate_unobtrusive_min_js = "~/Scripts/jquery.validate.unobtrusive.min.js"; 
                public const string npm_js = "~/Scripts/npm.js"; 
            }
        }
        public static partial class Content 
        {
            public static partial class images 
            {
                public static class Assets
                {
                }
            }
            public static partial class less 
            {
                public static partial class effects 
                {
                    public static partial class _2d_transitions 
                    {
                        public static class Assets
                        {
                        }
                    }
                    public static partial class background_transitions 
                    {
                        public static class Assets
                        {
                        }
                    }
                    public static partial class border_transitions 
                    {
                        public static class Assets
                        {
                        }
                    }
                    public static partial class curls 
                    {
                        public static class Assets
                        {
                        }
                    }
                    public static partial class icons 
                    {
                        public static class Assets
                        {
                        }
                    }
                    public static partial class shadow_and_glow_transitions 
                    {
                        public static class Assets
                        {
                        }
                    }
                    public static partial class speech_bubbles 
                    {
                        public static class Assets
                        {
                        }
                    }
                    public static class Assets
                    {
                    }
                }
                public static class Assets
                {
                }
            }
            public static partial class scss 
            {
                public static partial class effects 
                {
                    public static partial class _2d_transitions 
                    {
                        public static class Assets
                        {
                        }
                    }
                    public static partial class background_transitions 
                    {
                        public static class Assets
                        {
                        }
                    }
                    public static partial class border_transitions 
                    {
                        public static class Assets
                        {
                        }
                    }
                    public static partial class curls 
                    {
                        public static class Assets
                        {
                        }
                    }
                    public static partial class icons 
                    {
                        public static class Assets
                        {
                        }
                    }
                    public static partial class shadow_and_glow_transitions 
                    {
                        public static class Assets
                        {
                        }
                    }
                    public static partial class speech_bubbles 
                    {
                        public static class Assets
                        {
                        }
                    }
                    public static class Assets
                    {
                    }
                }
                public static class Assets
                {
                }
            }
            public static class Assets
            {
                public const string animate_css = "~/Content/animate.css";
                public const string animate_min_css = "~/Content/animate.min.css";
                public const string awesome_bootstrap_checkbox_css = "~/Content/awesome-bootstrap-checkbox.css";
                public const string bootstrap_theme_css = "~/Content/bootstrap-theme.css";
                public const string bootstrap_theme_min_css = "~/Content/bootstrap-theme.min.css";
                public const string bootstrap_css = "~/Content/bootstrap.css";
                public const string bootstrap_min_css = "~/Content/bootstrap.min.css";
                public const string font_awesome_css = "~/Content/font-awesome.css";
                public const string font_awesome_min_css = "~/Content/font-awesome.min.css";
                public const string hover_min_css = "~/Content/hover-min.css";
                public const string hover_css = "~/Content/hover.css";
            }
        }
    }
}

[GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
internal static class T4MVCHelpers {
    // You can change the ProcessVirtualPath method to modify the path that gets returned to the client.
    // e.g. you can prepend a domain, or append a query string:
    //      return "http://localhost" + path + "?foo=bar";
    private static string ProcessVirtualPathDefault(string virtualPath) {
        // The path that comes in starts with ~/ and must first be made absolute
        string path = VirtualPathUtility.ToAbsolute(virtualPath);
        
        // Add your own modifications here before returning the path
        return path;
    }

    // Calling ProcessVirtualPath through delegate to allow it to be replaced for unit testing
    public static Func<string, string> ProcessVirtualPath = ProcessVirtualPathDefault;

    // Calling T4Extension.TimestampString through delegate to allow it to be replaced for unit testing and other purposes
    public static Func<string, string> TimestampString = System.Web.Mvc.T4Extensions.TimestampString;

    // Logic to determine if the app is running in production or dev environment
    public static bool IsProduction() { 
        return (HttpContext.Current != null && !HttpContext.Current.IsDebuggingEnabled); 
    }
}





#endregion T4MVC
#pragma warning restore 1591, 3008, 3009, 0108


